# Generated by Django 2.2.2 on 2020-01-10 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.EmailField(max_length=100)),
                ('contact1', models.IntegerField()),
                ('contact2', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('cname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Delievery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Paymethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmname', models.CharField(max_length=100)),
                ('pvalue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('subheading', models.CharField(max_length=100)),
                ('actualprice', models.FloatField()),
                ('discount', models.FloatField()),
                ('highlight', models.TextField(max_length=500)),
                ('description', models.FilePathField()),
                ('companyname', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=50)),
                ('availability', models.BooleanField()),
                ('modelno', models.CharField(max_length=100)),
                ('catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp4.Category')),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp4.Material')),
                ('optionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp4.Option')),
                ('versionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp4.Variant')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.CharField(max_length=200)),
                ('image2', models.CharField(max_length=200)),
                ('image3', models.CharField(max_length=200)),
                ('image4', models.CharField(max_length=200)),
                ('image5', models.CharField(max_length=200)),
                ('image6', models.CharField(max_length=200)),
                ('image7', models.CharField(max_length=200)),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp4.Product')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp4.Field'),
        ),
    ]
