# Generated by Django 2.2.7 on 2020-01-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conname', models.CharField(max_length=100)),
                ('emailid', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=255)),
            ],
        ),
    ]
