# Generated by Django 2.2.7 on 2020-01-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp4', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pid',
            field=models.IntegerField(),
        ),
    ]
