# Generated by Django 2.2.2 on 2020-01-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp4', '0003_auto_20200113_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='ptype',
        ),
        migrations.AlterField(
            model_name='image',
            name='itemid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='catid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='mid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='optionid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='versionid',
            field=models.CharField(max_length=100),
        ),
    ]
